### ISSUE TITLE
Cant run the quick example

### ISSUE THREAD

**Issue by bobmoff** [bilalakil/mongoose-mutex#1]
/Users/xxxxxxxx/mutex-test.js:10
    .then(function(free) {
     ^
TypeError: undefined is not a function

Using:
iojs 1.8.1 (also tried 2.3.1)
mongoose 4.0.3

**Comment by bilalakil** [comment]
@bobmoff, thanks for bringing this issue up.

Unfortunately I probably won't be able to merge your pull request:
https://github.com/bilalakil/mongoose-mutex/pull/2

This is because if the promise is directly returned, then you no longer have access to the MongooseMutex object. For instance:

    > var x = new MongooseMutex('test'); // This will be a promise, not a MongooseMutex object
    > x.free
    undefined

The problem you've identified is actually a typo in the quick reference. Lets take a look at a different example in the current documentation. This is the first snippet under "#claim()":

    new MongooseMutex('slug3').promise
        .then(function(free) {
            ...
            return free();
        });

Here you can see what was missing from the quick reference: `new MongooseMutex('slug3').**promise**`.

Although this isn't as succinct as if we made the constructor return a promise directly, I think it's the better option as access to the properties of the MongooseMutex object is important.

That being said, I appreciate your help in discovering this issue and I'll update the documentation accordingly, right now.

**Comment by bilalakil** [comment]
Note to self: next time close issue AFTER pushing the fix.

**Comment by bobmoff** [comment]
ok. thanks for the quick reply :+1:

**Comment by bilalakil** [comment]
Thank you @bobmoff - I edited the initial reply adding more details if you're interested.

**Comment by bobmoff** [comment]
Ah.. To be honest I didn't even run the tests. I am kind of new to PR's. I should probably have done that Every day I live and I learn ;)
